// questions.js - Geopolitics 2026 Edition
// FUTURE UPDATE INSTRUCTION: Just replace the data inside the [...] brackets below.

window.LOCAL_DATA = [
  { "dataset": "SET_A", "topic": "Global Power", "q_type": "CONCEPT", "weight": 1, "question_text": "Primary driver of 2026 geopolitics?", "hint": "💡 Competition.", "explanation": "✅ Multipolar rivalry is correct. ❌ Unipolarity is over. ❌ Global unity is a myth.", "swipe_up_label": "Unipolar", "swipe_right_label": "Multipolar", "swipe_down_label": "HINT", "swipe_left_label": "Unity", "correct": "RIGHT" },
  { "dataset": "SET_A", "topic": "US-China", "q_type": "CONCEPT", "weight": 1, "question_text": "Core US-China tension area?", "hint": "💡 Tech + Security.", "explanation": "✅ Tech dominance (chips/AI) drives rivalry. ❌ Culture is secondary.", "swipe_up_label": "Culture", "swipe_right_label": "Tourism", "swipe_down_label": "HINT", "swipe_left_label": "Tech War", "correct": "LEFT" },
  { "dataset": "SET_B", "topic": "Ukraine", "q_type": "APPLICATION", "weight": 2, "question_text": "Ukraine war impact on Europe?", "hint": "💡 Security architecture.", "explanation": "✅ Energy insecurity reshaped policy. ❌ Economic isolation is false.", "swipe_up_label": "Isolation", "swipe_right_label": "Energy Shock", "swipe_down_label": "HINT", "swipe_left_label": "Neutrality", "correct": "RIGHT" },
  { "dataset": "SET_B", "topic": "Middle East", "q_type": "CONCEPT", "weight": 2, "question_text": "Key Middle East trend?", "hint": "💡 Deals > War.", "explanation": "✅ Regional normalization via diplomacy. ❌ Total war is avoided.", "swipe_up_label": "Total War", "swipe_right_label": "Isolation", "swipe_down_label": "HINT", "swipe_left_label": "Normalization", "correct": "LEFT" },
  { "dataset": "SET_B", "topic": "Indo-Pacific", "q_type": "APPLICATION", "weight": 2, "question_text": "Why is Indo-Pacific strategic?", "hint": "💡 Trade routes.", "explanation": "✅ Sea lanes control global trade flow. ❌ Tourism is minor.", "swipe_up_label": "Climate", "swipe_right_label": "Sea Lanes", "swipe_down_label": "HINT", "swipe_left_label": "Tourism", "correct": "RIGHT" },
  { "dataset": "SET_C", "topic": "Energy", "q_type": "CONCEPT", "weight": 3, "question_text": "Energy transition causes?", "hint": "💡 Geopolitics.", "explanation": "✅ Resource realignment (minerals vs oil). ❌ Energy peace is unlikely.", "swipe_up_label": "Peace", "swipe_right_label": "Oil Monopoly", "swipe_down_label": "HINT", "swipe_left_label": "Realignment", "correct": "LEFT" },
  { "dataset": "SET_A", "topic": "Global South", "q_type": "CONCEPT", "weight": 1, "question_text": "Global South rise due to?", "hint": "💡 Demographics.", "explanation": "✅ Economic/Population growth. ❌ Military dominance is weak.", "swipe_up_label": "Military", "swipe_right_label": "Growth", "swipe_down_label": "HINT", "swipe_left_label": "Ideology", "correct": "RIGHT" },
  { "dataset": "SET_B", "topic": "Tech", "q_type": "APPLICATION", "weight": 2, "question_text": "Why are chips strategic?", "hint": "💡 Compute power.", "explanation": "✅ Economic/Military security depends on semi-conductors.", "swipe_up_label": "Fashion", "swipe_right_label": "Security", "swipe_down_label": "HINT", "swipe_left_label": "Prestige", "correct": "RIGHT" },
  { "dataset": "SET_C", "topic": "Africa", "q_type": "CONCEPT", "weight": 3, "question_text": "Africa's 2026 value?", "hint": "💡 Critical Minerals.", "explanation": "✅ Strategic resources (Cobalt/Lithium). ❌ Isolation is false.", "swipe_up_label": "Isolation", "swipe_right_label": "Alliances", "swipe_down_label": "HINT", "swipe_left_label": "Resources", "correct": "LEFT" },
  { "dataset": "SET_B", "topic": "Cyber", "q_type": "CONCEPT", "weight": 2, "question_text": "Cyber warfare target?", "hint": "💡 Grid/Banks.", "explanation": "✅ Critical Infrastructure is the main target. ❌ Troops are secondary.", "swipe_up_label": "Troops", "swipe_right_label": "Infrastructure", "swipe_down_label": "HINT", "swipe_left_label": "Farms", "correct": "RIGHT" }
];

